### ISSUE TITLE
Add to startup?

### ISSUE THREAD

**Issue by Dontmindmes** [xan105/go-dll-regedit#1]
Hey could you post an example of adding a file to startup?

**Comment by xan105** [comment]
The following key are used to do that :

    HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
    HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
    HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce
    HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunOnce
    
cf: https://docs.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys

So writing to the registry ... 
```go
RegWriteStringValue("HKCU","Software\\Microsoft\\Windows\\CurrentVersion\\Run","YOURAPPNAME","PATH\\TO\\EXECUTABLE")
```

Note that you'll need admin rights to write outside of HKCU.

**Comment by Dontmindmes** [comment]
So for me to use that bottem code I have to have Admin?

**Comment by xan105** [comment]
No my example uses HKCU (HKEY_CURRENT_USER) so it doesn't need admin rights.

You can replace HKCU by :
HKCR
HKLM
HKU
HKCC

**Comment by Dontmindmes** [comment]
Ahhh thank you!!!!

Btw I tried but couldn't quite get it to remove from startup programmatically HKCU

**Comment by xan105** [comment]
Here is a quick node.js (v10.10.0) working example to show you :
- writing to HKCU\Software\Microsoft\Windows\CurrentVersion\Run
- reading the written key
- deleting the key

[example.zip](https://github.com/xan105/go-dll-regedit/files/3364874/example.zip)

Here are the correct api syntax just in case : 
```js
regedit.RegWriteStringValue("HKCU","Software\\Microsoft\\Windows\\CurrentVersion\\Run","HELLOWORLD","C:\\awesome.exe");

regedit.RegQueryStringValue("HKCU","Software\\Microsoft\\Windows\\CurrentVersion\\Run","HELLOWORLD");

regedit.RegDeleteKeyValue("HKCU","Software\\Microsoft\\Windows\\CurrentVersion\\Run","HELLOWORLD");
```

**Comment by Dontmindmes** [comment]
btw so when iwant to build a exe

i have to do 

> go build -buildmode=c-shared -o regedit.dll registry_dll

?? and it will generate a dll file and a exe file that must remain togethor??

**Comment by xan105** [comment]
No this code is solely to be compiled into a dll. 
Either you do it yourself with : 

> go build -buildmode=c-shared -o regedit.dll registry_dll

or you download the precompiled version here : 
https://github.com/xan105/go-dll-regedit/releases

Then you can use this dll in any language that have C bindings like dll import feature.

However if you are writing a golang exe then look at the source and write your own method based on it.
Because I don't think you can have 2 Go runtimes coexisting in a single process.
